---
title: Paradise
timezone: UTC
collections:
  journals:
    title: Journals
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: journals
  values:
    layout: journal
    image: ''
    images:
    - image: ''
      alt: ''
    hide-title: ''
- scope:
    path: ''
    type: projects
  values:
    layout: project
tagline:
url: http://studioparadise.com
social-image:
social-description: "Hey you've found Paradise - not that type of Paradise, put your clothes back on, but feel free to say hello."
facebook: studioparadisenyc
twitter: paradisenewyork
instagram: studioparadisenyc
linkedin: studio-paradise
behance: studioparadise
studio:
  clients:
  - name: Jack Erwin
    project: Jack Erwin
  - name: Saturdays
    project: Saturdays
  - name: Mikoh
    project: Mikoh
  - name: Dudleys
  - name: Express
  - name: Convicts
    project: Convicts
  - name: Kaelen
    project: Kaelen
  - name: Flower Shop
    project: Flower Shop
  - name: Abbott
  - name: Well Well
  - name: Tsovet
  - name: FLWR
  - name: Raen
  - name: Leader Bag Co.
    project: Leader Bag
index-slider-images:
- image: "/uploads/1JE_Home.jpg"
  alt:
  project: Jack Erwin
- image: "/uploads/Mikoh_HomepageHero_20160803.jpg"
  alt:
  project: miko
- image: "/uploads/Kaelen_HomepageHero_20160803.jpg"
  alt:
  project: Kaelen
- image: "/uploads/Leader_HomepageHero_20160803.jpg"
  alt:
  project: Leader Bag
- image: "/uploads/Prize_HomepageHero_20160803.jpg"
  alt:
  project: Prize
- image: "/uploads/Saturdays_HomepageHero_20160803.jpg"
  alt:
  project: Saturdays
gems:
- jekyll-coffeescript
exclude:
- README.md
- node_modules
- gruntfile.js
- package.json
- vendor/
