---
title: Paradise
timezone: UTC
collections:
  journals:
    title: Journals
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: journals
  values:
    layout: journal
    image: ''
    images:
    - image: ''
      alt: ''
    hide-title: ''
- scope:
    path: ''
    type: projects
  values:
    layout: project

tagline: Changing the world, one uninspired quote at a time
url: http://yourwebsite.com
socialimg: "/img/social.jpg"
facebook: fbusername
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername
phone: 
email: 
index-slider-images:
- image: 
  alt: 
  project: Jack Erwin
gems:
- jekyll-coffeescript
exclude:
- README.md
- node_modules
- gruntfile.js
- package.json
- vendor/
