---
title: Paradise
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    layout: project
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: default
    modules:
    - type: hero
      title: ''
      image: ''
    - type: text
      text: 
      variation: centered
    - type: images
      image1: ''
      image2: ''
tagline: Changing the world, one uninspired quote at a time
url: http://yourwebsite.com
socialimg: "/img/social.jpg"
facebook: fbusername
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername
phone: 
email: 
exclude:
- README.md
- node_modules
- gruntfile.js
- package.json
- vendor/
gems:
- jekyll-coffeescript
