---
title: Pariah Website
timezone: UTC
collections:
  journals:
    title: Journals
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: journals
  values:
    layout: journal
    image: ''
    images:
    - image: ''
      alt: ''
    hide-title: ''
- scope:
    path: ''
    type: projects
  values:
    layout: project
tagline: 
url: http://studioparadise.com
social-image: "/uploads/STUDIO_PARIAH_v3-d6f00d.png"
social-description: Hey you've found Paradise - not that type of Paradise, put your
  clothes back on, but feel free to say hello.
vimeo_url: https://vimeo.com/user43280791
instagram: studiopariah
linkedin: studio-pariah
behance: 
studio:
  clients:
  - name: Thom Browne
  - name: Merrell
  - name: The 5th
  - name: Temme Media
  - name: Marc Jacobs
  - name: RVCA
  - name: Nixon
  - name: Akin Creative
  - name: Jack Erwin
    project: Jack Erwin
  - name: Saturdays
    project: Saturdays
  - name: Mikoh
    project: Mikoh
  - name: Dudleys
  - name: Express
  - name: Convicts
    project: Convicts
  - name: Kaelen
    project: Kaelen
  - name: Flower Shop
    project: Flower Shop
  - name: Abbott
  - name: Well Well
  - name: Tsovet
  - name: FLWR
  - name: Raen
  - name: Leader Bag Co.
    project: Leader Bag
index-slider-images:
- image: "/uploads/HERO_IMAGE.jpg"
  alt: 
  project: 
- image: "/uploads/HERO_IMAGE2.jpg"
  alt: 
  project: 
- image: "/uploads/HERO_IMAGE3.jpg"
  alt: 
  project: 
- image: "/uploads/HERO_IMAGE4.jpg"
  alt: 
  project: 
- image: "/uploads/Prize_HomepageHero_20160803.jpg"
  alt: 
  project: Prize
- image: "/uploads/Saturdays_HomepageHero_20160803.jpg"
  alt: 
  project: Saturdays
gems:
- jekyll-coffeescript
exclude:
- README.md
- node_modules
- gruntfile.js
- package.json
- vendor/
